// A mode is usable only when its provenance matches the current Japanese source.
// Legacy _nodic values may have been generated by the former hybrid fallback.
export const translationField = (
  entity,
  field,
  language,
  mode = "dictionary"
) => {
  const source = entity?.[`${field}_ja`] || entity?.[field] || "";
  if (language === "ja") return { text: source, status: "original" };
  const key = `${field}_${language}${mode === "deepl_only" ? "_nodic" : ""}`;
  const text = entity?.[key];
  const metadata = entity?.[`${key}_translation`];
  if (!text) return { text: source, status: "missing" };
  if (
    !metadata ||
    metadata.schemaVersion !== 1 ||
    metadata.mode !== mode ||
    metadata.sourceText !== source
  )
    return { text: source, status: "unverified" };
  if (!["ready", "partial"].includes(metadata.status))
    return { text: source, status: "failed" };
  if (
    mode === "deepl_only" &&
    (metadata.usedDictionary !== false ||
      !["deepl_only", "passthrough"].includes(metadata.method))
  )
    return { text: source, status: "unverified" };
  return { text, status: metadata.status };
};

export const translationStatusLabel = (status, language) => {
  if (["original", "ready"].includes(status)) return "";
  const labels = {
    en: {
      missing: "Translation unavailable; Japanese original",
      unverified: "Translation unverified; Japanese original",
      failed: "Translation failed; Japanese original",
      partial: "Partial reference translation; cannot compare",
    },
    zh: {
      missing: "未生成翻译；日文原文",
      unverified: "翻译未验证；日文原文",
      failed: "翻译失败；日文原文",
      partial: "含原文的参考翻译；不可比较",
    },
  };
  return labels[language]?.[status] || "原文を含む参考表示・比較不可";
};
export const translationDisplay = (
  entity,
  field,
  language,
  mode = "dictionary"
) => {
  const { text, status } = translationField(entity, field, language, mode);
  const label = translationStatusLabel(status, language);
  return text && label ? `${text} [${label}]` : text;
};
